[package]
name = "brainfuck_plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brainfuck_plus-core = {git = "https://github.com/F1L1Pv2/brainfuck_plus-core"}