[package]
name = "brainfuck_plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brainfuck_plus-core = "0.1.36"
# brainfuck_plus-core = {path="../brainfuck_plus-core"}